version: '3.8'

services:
  auth:
    build: ./auth
    container_name: auth_service
    ports:
      - '3001:3001'
    env_file:
      - ./auth/.env
    volumes:
      - ./auth:/app
      - /app/node_modules

  event:
    build: ./event
    container_name: event_service
    ports:
      - '3002:3002'
    env_file:
      - ./event/.env
    volumes:
      - ./event:/app
      - /app/node_modules
    depends_on:
      - auth

  gateway:
    build: ./gateway
    container_name: gateway_service
    ports:
      - '3000:3000'
    env_file:
      - ./gateway/.env
    volumes:
      - ./gateway:/app
      - /app/node_modules
    depends_on:
      - auth
      - event
