version: '3.8'

services:
  auth:
    build: ./auth
    container_name: auth_service
    ports:
      - '3001:3001'
    env_file:
      - ./auth/.env
    volumes:
      - ./auth:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - backend

  event:
    build: ./event
    container_name: event_service
    ports:
      - '3002:3002'
    env_file:
      - ./event/.env
    volumes:
      - ./event:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - backend

  gateway:
    build: ./gateway
    container_name: gateway_service
    ports:
      - '3000:3000'
    env_file:
      - ./gateway/.env
    volumes:
      - ./gateway:/app
      - /app/node_modules
    depends_on:
      - auth
      - event
    networks:
      - backend

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    networks:
      - backend

  e2e_runner:
    build: ./e2e-runner
    container_name: e2e_runner
    depends_on:
      - gateway
      - auth
      - event
    networks:
      - backend
    command: ["npm", "run", "test:e2e"]  # 여기서 e2e 테스트 명령어를 실행

networks:
  backend:
    driver: bridge
